spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: jhj
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug